# Generated by Django 4.2.5 on 2023-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_students_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
